### ISSUE TITLE
Invalid url

### ISSUE THREAD

**Issue by NeptuneQ** [mcu8/OpenModManager#1]
If I try to click the "Already Released?" button and then input my workshop url, the software displays an invalid url. Mods uploaded using the official mod manager are normal
![ModdingTools_YToQA8uelY.png](https://i.loli.net/2020/07/02/xuf3hSknDgmaOUN.png)

**Comment by mcu8** [comment]
In the latest release, that button is moved to the "Uploader options" window, it should work here.
