### ISSUE TITLE
[b139] (Asset Exporter) Invalid input at line 1!

### ISSUE THREAD

**Issue by Un-Drew** [mcu8/OpenModManager#4]
For some reason the Asset Exporter doesn't like this asset's name:
![image](https://user-images.githubusercontent.com/69184314/142755423-9728d7a8-f3db-4bd2-ad40-4b228ca17acd.png)

Asset name: `Texture2D'HatInTime_Levels_DarkForest_V.Textures.Snatcher-Table'`

**Comment by mcu8** [comment]
Fixed
https://github.com/mcu8/OpenModManager/commit/f397706a4f4339bba5465df28de0343f666dd0f5
