### ISSUE TITLE
Mod Manager.exe

### ISSUE THREAD

**Issue by Felipe210ik** [mcu8/OpenModManager#6]
That's the question, the first question is. Why Mod Manager.Exe Not here

**Comment by Un-Drew** [comment]
Hey! I'm guessing you're referring to ModManager.exe that's included in the steam modding tools? OpenModManager is a completely separate mod manager, written from scratch, and has no correlation or dependency to the original mod manager owned by Gears for Breakfast. Including that here would be both redundant, and possibly illegal...?

**Comment by mcu8** [comment]
Although OpenModManager does not require ModManager.exe to function, it still needs the rest of the game's modding environment. Therefore, you need to download it through Steam under the tools section.
